# Generated by Django 6.0 on 2025-12-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Categorie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
