# Generated by Django 5.0.4 on 2025-12-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_delivery_address_order_delivery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_to_cart',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='add_to_cart_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myapp.register'),
        ),
        migrations.AlterUniqueTogether(
            name='add_to_cart',
            unique_together={('user', 'add_to_cart_product')},
        ),
    ]
