# Generated by Django 5.0.4 on 2025-12-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order_payment_status_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerimg1', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('bannerimg2', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('bannervideo', models.FileField(blank=True, null=True, upload_to='uploads/banners/videos/')),
            ],
        ),
    ]
